/*
 * Read-only presentation projection of the canonical HoloForge fixtures.
 * Contract validation remains in src/; this browser-safe projection is
 * regression-checked against those fixtures in Node tests.
 */
export const prototypeScenarios = Object.freeze([
  Object.freeze({
    id: 'hierarchy-first',
    title: 'Hierarchy Focus',
    interpretation: 'Increase headline dominance while preserving locked brand marks.',
    score: 0.92,
    baseline: 0.95,
    gap: 0.029999999999999916,
    durationMs: 12,
    objective: 'hierarchy-balance-v1',
    seed: 'hierarchy-seed-001',
    backend: 'vaelon',
    algorithm: 'deterministic-candidate-v1',
    baselineBackend: 'classical-reference',
    baselineAlgorithm: 'exact-reference-v1',
    status: 'complete',
    hardConstraintsPassed: true,
    tradeoff: 'Slightly increases vertical separation to improve hierarchy.',
    changed: 2,
    sourceSnapshotId: 'snapshot-v1',
    sourceSnapshotFingerprint: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    optimizationFingerprint: '93eeaeed3f0a33c07a96284a6938d81043f879bc0ad2718f7ac2737ad6f1ed0b',
    scenarioFingerprint: 'c918c2796610e5125863bad2c885943dae744ceb1cbf0ea9055e194c448a4f35',
    target: 'web-dashboard',
  }),
  Object.freeze({
    id: 'spacing-balance',
    title: 'Spatial Balance',
    interpretation: 'Improve spacing rhythm and edge balance with minimal movement.',
    score: 84,
    baseline: 86,
    gap: 2,
    durationMs: 12,
    objective: 'spacing-balance-v1',
    seed: 'spacing-seed-001',
    backend: 'vaelon',
    algorithm: 'deterministic-candidate-v1',
    baselineBackend: 'classical-reference',
    baselineAlgorithm: 'exact-reference-v1',
    status: 'complete',
    hardConstraintsPassed: true,
    tradeoff: 'Preserves content order while increasing lateral balance.',
    changed: 2,
    sourceSnapshotId: 'snapshot-v1',
    sourceSnapshotFingerprint: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    optimizationFingerprint: 'cab3933331a61b7b9ffc4c82bdaf428f41780a2e17c9ee1e1cdc8337c8270b9f',
    scenarioFingerprint: 'd23a31c704978ff6f6723f3af7eec7d50d0d9f74e4ac833de888dcc3ed2a3eba',
    target: 'web-dashboard',
  }),
  Object.freeze({
    id: 'locked-brand',
    title: 'Brand-Safe Reflow',
    interpretation: 'Reflow supporting content without moving protected brand elements.',
    score: 0.88,
    baseline: 0.9,
    gap: 0.020000000000000018,
    durationMs: 12,
    objective: 'brand-safe-reflow-v1',
    seed: 'brand-seed-001',
    backend: 'vaelon',
    algorithm: 'deterministic-candidate-v1',
    baselineBackend: 'classical-reference',
    baselineAlgorithm: 'exact-reference-v1',
    status: 'complete',
    hardConstraintsPassed: true,
    tradeoff: 'Keeps protected brand geometry fixed while rebalancing support copy.',
    changed: 2,
    sourceSnapshotId: 'snapshot-v1',
    sourceSnapshotFingerprint: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    optimizationFingerprint: '2d0ad8a2c8b02fc21ec3b04e9614db5f8bf8f53a8f0d7d027d7ea01df827bf55',
    scenarioFingerprint: '5f3e25a6ffb7bca08a06bdaa2e5281824af17ef428a790fc90b5d64aaa2c45f8',
    target: 'web-dashboard',
  }),
]);
