import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import assert from 'node:assert/strict';

const WORKFLOW = new URL('../../.github/workflows/materialize-v115.yml', import.meta.url);

test('authenticated materialization is current-main and pull-request gated', async () => {
  const workflow = await readFile(WORKFLOW, 'utf8');

  assert.match(workflow, /branches: \["main"\]/u);
  assert.match(workflow, /ref: main/u);
  assert.match(workflow, /pull-requests:\s*write/u);
  assert.match(workflow, /gh pr create/u);
  assert.match(workflow, /automation\/materialize-authenticated-v115/u);
  assert.doesNotMatch(workflow, /score-maximization/u);
  assert.doesNotMatch(workflow, /git push origin HEAD:/u);
});

test('materialization verifies provenance before publishing generated bytes', async () => {
  const workflow = await readFile(WORKFLOW, 'utf8');

  const materialize = workflow.indexOf('python scripts/materialize_v115.py');
  const verifyArchive = workflow.indexOf('python -m archive_verifier');
  const publish = workflow.indexOf('Publish reviewed materialization change');

  assert.ok(materialize >= 0);
  assert.ok(verifyArchive > materialize);
  assert.ok(publish > verifyArchive);
});
