from __future__ import annotations

from typing import Protocol

from models import ExportArtifact, ExportJob
from repositories import OwnedKey


class JobRepositoryContract(Protocol):
    def put(self, job: ExportJob) -> None: ...
    def get(self, key: OwnedKey) -> ExportJob | None: ...
    def find_by_export(self, *, user_id: str, brand_id: str, export_id: str) -> ExportJob | None: ...
    def recover_stale_jobs() -> int: ...


class ArtifactRepositoryContract(Protocol):
    def put(self, artifact: ExportArtifact) -> None: ...
    def get(self, key: OwnedKey) -> ExportArtifact | None: ...
